# -*- coding: utf-8 -*-
# *** Spyder Python Console History Log ***

## ---(Mon Mar 21 18:27:55 2022)---
runfile('C:/Users/Dell/.spyder-py3/temp.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/untitled0.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/download.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/download_pdf.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/httpsdownload.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/fileList.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/untitled6.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/db_trial.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/db_2.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/logging.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/lgpy.py', wdir='C:/Users/Dell/.spyder-py3')

## ---(Wed Apr 27 09:45:20 2022)---
runfile('C:/Users/Dell/.spyder-py3/lgpy.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
print(et_sess.get_result("mAK47Dg5veYvNLoTUT6H7WldpRohKFfVXyQTqEFR_Lowd1mwIUU_1652959847_3"))
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/largeFile.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
%clear
runfile('C:/Users/Dell/.spyder-py3/lgpy.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/lg_chk.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/largeFile.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Multi_Log.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/m_logs.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Multi_Log.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/m_logs.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/mLog.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')

## ---(Fri Jun 10 12:23:54 2022)---
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/untitled0.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')

## ---(Fri Jul 15 19:20:54 2022)---
runfile('C:/Users/Dell/.spyder-py3/read_from_textfile.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
%clear
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/read_from_textfile.py', wdir='C:/Users/Dell/.spyder-py3')
%clear
runfile('C:/Users/Dell/.spyder-py3/read_from_textfile.py', wdir='C:/Users/Dell/.spyder-py3')
%clear
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')

## ---(Tue Aug 16 13:11:00 2022)---
runfile('C:/Users/Dell/.spyder-py3/db_trial.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/check_usage.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getresults.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/check_usage.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_un_Std.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')

## ---(Mon Nov 14 09:59:01 2022)---
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_pdf_tables.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_standard.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/db_2.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getUsage.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/propertyFile.py', wdir='C:/Users/Dell/.spyder-py3')
pip install jproperties
runfile('C:/Users/Dell/.spyder-py3/propertyFile.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ExtractSingleFile.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/propertyFile.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/Extract_table.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/getTransactions.py', wdir='C:/Users/Dell/.spyder-py3')
runfile('C:/Users/Dell/.spyder-py3/ResultPrint.py', wdir='C:/Users/Dell/.spyder-py3')